# Generated by Django 5.2.17 on 2026-09-16 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('year', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('GROUP_STAGE', 'Group stage'), ('KNOCKOUT', 'Knockout'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=16)),
                ('group_count', models.PositiveSmallIntegerField()),
                ('teams_per_group', models.PositiveSmallIntegerField()),
                ('qualifiers_per_group', models.PositiveSmallIntegerField()),
                ('third_place_enabled', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-year', 'name', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('group_count__gte', 1)), name='competition_group_count_gte_1'), models.CheckConstraint(condition=models.Q(('teams_per_group__gte', 2)), name='competition_teams_per_group_gte_2'), models.CheckConstraint(condition=models.Q(('qualifiers_per_group__gte', 1)), name='competition_qualifiers_gte_1'), models.CheckConstraint(condition=models.Q(('qualifiers_per_group__lte', models.F('teams_per_group'))), name='competition_qualifiers_lte_teams')],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.PositiveSmallIntegerField()),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='competitions.competition')),
            ],
            options={
                'ordering': ['competition_id', 'ordinal'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('kind', models.CharField(choices=[('REGULAR', 'Regular'), ('FINAL', 'Final'), ('THIRD_PLACE', 'Third place')], default='REGULAR', max_length=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed')], default='PENDING', max_length=10)),
                ('source_outcome_a', models.CharField(blank=True, choices=[('WINNER', 'Winner'), ('LOSER', 'Loser')], max_length=6, null=True)),
                ('source_outcome_b', models.CharField(blank=True, choices=[('WINNER', 'Winner'), ('LOSER', 'Loser')], max_length=6, null=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='competitions.group')),
                ('source_match_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='dependents_as_team_a', to='competitions.match')),
                ('source_match_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='dependents_as_team_b', to='competitions.match')),
            ],
            options={
                'ordering': ['round_id', 'position'],
            },
        ),
        migrations.CreateModel(
            name='RosterMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_memberships', to='competitions.competition')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roster_memberships', to='competitions.player')),
            ],
            options={
                'ordering': ['team_id', 'player__name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PlayerMatchStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.PositiveSmallIntegerField(default=0)),
                ('assists', models.PositiveSmallIntegerField(default=0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='competitions.match')),
                ('roster_membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='match_stats', to='competitions.rostermembership')),
            ],
            options={
                'ordering': ['match_id', 'roster_membership_id'],
            },
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('GROUP', 'Group'), ('KNOCKOUT', 'Knockout')], max_length=8)),
                ('number', models.PositiveSmallIntegerField()),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='competitions.competition')),
            ],
            options={
                'ordering': ['competition_id', 'stage', 'number'],
            },
        ),
        migrations.AddField(
            model_name='match',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='competitions.round'),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='competitions.competition')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='rostermembership',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_memberships', to='competitions.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='shootout_winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shootout_wins', to='competitions.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matches_as_team_a', to='competitions.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team_b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matches_as_team_b', to='competitions.team'),
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draw_lots_priority', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='competitions.group')),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='group_membership', to='competitions.team')),
            ],
            options={
                'ordering': ['group_id', 'team__name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TeamMatchStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('own_goals_received', models.PositiveSmallIntegerField(default=0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_stats', to='competitions.match')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='match_stats', to='competitions.team')),
            ],
            options={
                'ordering': ['match_id', 'team_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.UniqueConstraint(fields=('competition', 'ordinal'), name='unique_group_ordinal_per_competition'),
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.CheckConstraint(condition=models.Q(('ordinal__gte', 1)), name='group_ordinal_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='playermatchstat',
            constraint=models.UniqueConstraint(fields=('match', 'roster_membership'), name='unique_player_stat_per_match'),
        ),
        migrations.AddConstraint(
            model_name='round',
            constraint=models.UniqueConstraint(fields=('competition', 'stage', 'number'), name='unique_round_number_per_stage'),
        ),
        migrations.AddConstraint(
            model_name='round',
            constraint=models.CheckConstraint(condition=models.Q(('number__gte', 1)), name='round_number_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('competition', 'name'), name='unique_team_name_per_competition'),
        ),
        migrations.AddConstraint(
            model_name='rostermembership',
            constraint=models.UniqueConstraint(fields=('competition', 'player'), name='unique_player_roster_per_competition'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['group', 'status'], name='match_group_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(fields=('round', 'position'), name='unique_match_position_per_round'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(condition=models.Q(('position__gte', 1)), name='match_position_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(condition=models.Q(('team_a__isnull', True), ('team_b__isnull', True), models.Q(('team_a', models.F('team_b')), _negated=True), _connector='OR'), name='match_teams_must_differ'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'PENDING'), models.Q(('team_a__isnull', False), ('team_b__isnull', False)), _connector='OR'), name='completed_match_has_teams'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('source_match_a__isnull', True), ('source_outcome_a__isnull', True)), models.Q(('source_match_a__isnull', False), ('source_outcome_a__isnull', False)), _connector='OR'), name='match_source_a_fields_together'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('source_match_b__isnull', True), ('source_outcome_b__isnull', True)), models.Q(('source_match_b__isnull', False), ('source_outcome_b__isnull', False)), _connector='OR'), name='match_source_b_fields_together'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(condition=models.Q(('shootout_winner__isnull', True), models.Q(('team_a__isnull', False), ('shootout_winner', models.F('team_a'))), models.Q(('team_b__isnull', False), ('shootout_winner', models.F('team_b'))), _connector='OR'), name='shootout_winner_is_participant'),
        ),
        migrations.AddConstraint(
            model_name='groupmembership',
            constraint=models.CheckConstraint(condition=models.Q(('draw_lots_priority__isnull', True), ('draw_lots_priority__gte', 1), _connector='OR'), name='group_membership_draw_priority_positive'),
        ),
        migrations.AddConstraint(
            model_name='teammatchstat',
            constraint=models.UniqueConstraint(fields=('match', 'team'), name='unique_team_stat_per_match'),
        ),
    ]
